### PR TITLE
Handle extraction of Uint63

### PR DESCRIPTION
**Pull request by Lysxia**
Also merges some updates from QuickChick...

### CODE REVIEW

**Review by liyishuai — DISMISSED** [review]

**Comment by Lysxia** [comment]
:facepalm: CircleCI is killing the build in the middle of installing coq... It's probably going OOM.

**Review by liyishuai — APPROVED** [review]

**Comment by Lysxia** [comment]
Does [dca99a2](https://github.com/Lysxia/coq-simple-io/pull/48/commits/dca99a2045bfea2f34f7c6969a552229e15804bc) mean that we won't get updates if say coq-ext-lib updates?

**Comment by liyishuai** [comment]
Since coq-ext-lib is installed from coq-extra-dev (which was fresh), we always get the latest version.

**Comment by Lysxia** [comment]
What about when the coq version is too old for coq-ext-lib.dev?

**Comment by liyishuai** [comment]
The Coq version is specified by the Docker tag. Coq should not be reinstalled or recompiled in CI stage.

**Comment by Lysxia** [comment]
Suppose you release coq-ext-lib.0.12.0 tomorrow and then coq-ext-lib.dev suddenly becomes compatible with only Coq 8.15. Will coq-ext-lib.0.12.0 be picked up by the build using Coq 8.14?

**Comment by liyishuai** [comment]
In that case we should either pin down ExtLib version per Coq version or disable extra-dev repo. I’d prefer the former.
SimpleIO is checked in ExtLib CI, so not that much to worry about.

**Pull request merged**
