### PR TITLE
Add Filename module

### PR DESCRIPTION
**Pull request by liyishuai**

### CODE REVIEW

**Comment by liyishuai** [comment]
Are there ways to test partial usability in older OCaml, and full usability in latest ones?

**Comment by Lysxia** [comment]
Would adding CI builds with older OCaml versions address that?

**Comment by liyishuai** [comment]
No with the current `test/TestExtraction.v`, which compiles all definitions. We could have Cppo handle OCaml-version-specific APIs though.

**Comment by liyishuai** [comment]
Maybe worth implementing the Sys functions in another PR.

**Comment by Lysxia** [comment]
In the meantime you can do `fail_with "not available on OCaml XYZ"`.

**Comment by Lysxia** [comment]
Oh I see you just removed them. OK

**Review by Lysxia — APPROVED** [review]

**Comment by liyishuai** [comment]
coq/opam-coq-archive#2303 requires this module. Consider releasing a tag soon?

**Comment by Lysxia** [comment]
OK, I just need to remove the primitive ints stuff so I don't have to worry about licensing.

**Pull request merged**
