### PR TITLE
Unix: add select and file_descr_eqb

### PR DESCRIPTION
**Pull request by liyishuai**

### CODE REVIEW

**Comment by Lysxia** [comment]
Can you rebase this now that there are better tests on master (#12)?

**Comment by liyishuai** [comment]
done

**Comment by liyishuai** [comment]
The added functions haven't appeared in the [documentation](https://lysxia.github.io/coq-simple-io/SimpleIO.IO_Unix.html).

**Comment by Lysxia** [comment]
Thanks for the reminder, I just uploaded a new version. I wish there were something better than coqdoc though...

**Pull request merged**
