### PR TITLE
More functions in Stdlib and Sys

### PR DESCRIPTION
**Pull request by liyishuai**
We now have extracted code with and without `Pervasives.`
Raises #17 again.
Also raises #30.

### CODE REVIEW

**Review by Lysxia — APPROVED** [review]

**Comment by Lysxia** [comment]
@SkySkimmer  That build seems to have pulled code from just before this PR, which should fix the issue. Can you try rerunning the job?

**Comment by SkySkimmer** [comment]
rerun started https://gitlab.com/coq/coq/-/jobs/1589346633

**Comment by SkySkimmer** [comment]
A different error:
~~~
File "./src/Mutation.v", line 4, characters 0-38:
Error:
File not found on loadpath : coqsimpleio_plugin.cmxs
~~~

**Comment by Lysxia** [comment]
Now simple-io and QuickChick should be fixed!

**Pull request merged**
